language: php
php:
- 5.3
before_script:
- curl -s http://getcomposer.org/installer | php
- composer --optimize-autoloader install
script: vendor/bin/phing test
deploy:
  provider: heroku
  api_key:
    secure: fB/IoKh4qiOaJ/d4kWS7Mokgpj5CevKdbSNF9qGFiQdjOMs1m/Ub2TX6Lo4jjkeNy2sU4TJX8gzjbJdkvdIO8Rej5e7KlZmw3chMZpUsU6Axy1QVEfnv8WZd7APexz+pJkX2yagXuZQcvsoOcSKp0YLE6Vif9W7rpMFM3olVd+8=
  app: hello-cd
  on:
    repo: xpeppers/hello-cd
